version: "4.0"
services:
  llm-node:
    build: .
    container_name: enterprise-inference-node
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    networks:
      - edge-network
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      # Define routing rule for the web app
      - "traefik.http.routers.llmapp.rule=PathPrefix(`/`)" 
      - "traefik.http.services.llmapp.loadbalancer.server.port=8000"
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: edge-ingress-tunnel
    command: tunnel --url http://traefik:80
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - edge-network

  postgres:
    image: postgres:16-alpine
    container_name: edge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: placeholder
      POSTGRES_DB: llmops
    ports:
      - "5432:5432"
    networks:
      - edge-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: edge-db-redis
    labels:
      - "traefik.enable=false"
    networks:
      - edge-network
    
  traefik:
    image: traefik:v3.2
    container_name: edge-lb
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - edge-network


networks:
  edge-network:
    driver: bridge

volumes:
  pgdata:
