version: "3.8"
services:
  llm-node:
    build: .
    container_name: enterprise-inference-node
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
    ports:
      - "8000:8000"
    depends_on:
      - cloudflared
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    networks:
      - edge-network
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      # Define routing rule for the web app
      - "traefik.http.routers.webapp.rule=Host(`edge-llmops.com`)" 
      - "traefik.http.services.webapp.loadbalancer.server.port=8000"
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: edge-ingress-tunnel
    command: tunnel --url http://llm-node:8000
    restart: unless-stopped
    depends_on:
      - llm-node
    networks:
      - edge-network

  redis:
    image: redis:alpine
    labels:
      - "traefik.enable=false"
    networks:
      - edge-network
    
  traefik:
    image: traefik:v3.2
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - edge-network


networks:
  edge-network:
    driver: bridge