services:
  llm-node:
    build: .
    container_name: enterprise-inference-node
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
    depends_on:
      - redis
      - postgres
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      PGUSER: postgres #Use Superaccount by Default, change if needed
      PGPASSWORD: placeholder #Replace wth your user password here
      PGDATABASE: llmops 
      PGHOST: edge-db
      PGPORT: 5432
    restart: unless-stopped
    networks:
      - edge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llmapp.rule=PathPrefix(`/`)" 
      - "traefik.http.services.llmapp.loadbalancer.server.port=8000"
      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: edge-ingress-tunnel
    command: tunnel --protocol http2 --url http://traefik:80
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - edge-network

  postgres:
    image: postgres:16-alpine
    container_name: edge-db
    environment:
      POSTGRES_USER: postgres #Use Superaccount by Default, change if needed
      POSTGRES_PASSWORD: placeholder #Replace wth your user password here
      POSTGRES_DB: llmops
    ports:
      - "5432:5432"
    networks:
      - edge-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: edge-db-redis
    labels:
      - "traefik.enable=false"
    networks:
      - edge-network
    
  traefik:
    image: traefik:v3.6.4
    container_name: edge-lb
    # user: root -> Optional for disparate OS
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--providers.docker.endpoint=unix:///var/run/docker.sock" -> Optional for disparate OS 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - edge-network

  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: edge-prom-logger
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    restart: unless-stopped
    networks:
      - edge-network

  grafana:
    image: grafana/grafana:10.3.3
    container_name: edge-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=enterprise_admin_2026
    restart: unless-stopped
    networks:
      - edge-network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

networks:
  edge-network:
    driver: bridge

volumes:
  pgdata:
  prom_data:
  grafana_data:
