apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-node
  template:
    metadata:
      labels:
        app: llm-node
    spec:
      containers:
        - name: fastapi-server
          image: llm-enterprise:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PGUSER
              value: "admin"
            - name: PGPASSWORD
              value: "secure_local_password"
            - name: PGHOST
              value: "postgres-service"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "llmops-ledger"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: SECRET_KEY
              value: "Ubdzme0qRYyVnqT8sZj2JNRTLyQtu56izQR6dpyAcvK"
            - name: LEMON_SQUEEZY_WEBHOOK_SECRET
              value: "placeholder"
          resources:
            limits:
              memory: "4Gi"
              # nvidia.com/gpu: "1" #Optional

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
      app: llm-node
