apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-node
  template:
    metadata:
      labels:
        app: llm-node
    spec:
      containers:
        - name: fastapi-server
          image: llm-enterprise:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_URL
              value: "postgresql+asyncpg://admin:secure_local_password@postgres-service:5432/llmops_ledger"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: SECRET_KEY
              value: "Ubdzme0qRYyVnqT8sZj2JNRTLyQtu56izQR6dpyAcvK"
            - name: LEMON_SQUEEZY_WEBHOOK_SERCRET
              value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NGQ1OWNlZi1kYmI4LTRlYTUtYjE3OC1kMjU0MGZjZDY5MTkiLCJqdGkiOiJhYWY2NmZjZjA1OThlYWQ0OGQ2MDVjMGFjNDdkZDExOTUzMWQzYmY3MmY5YjRmMzY0YTI0ZGE1NTc4ODNmNWYzNjFiZGYzZWMzNDNhNTI3OSIsImlhdCI6MTc3Mzc5NDAwMy40ODkwNDksIm5iZiI6MTc3Mzc5NDAwMy40ODkwNTEsImV4cCI6MTc4OTg2MjQwMC4wMzIyMiwic3ViIjoiNjcyNDczNCIsInNjb3BlcyI6W119.UrWmbQ1U8OVi00gEQrw4o5MLrVTTMipzyNz0-KplOOw0jn1AVIoghodvHXQSrTjnleVlIQ3wmbcDE02NiR5HVVuZerKEPANjV4w81lS6haMjlfPtfWRbhYVdoGLGX1hBsFWTn0POYp-0JgAPagh-v2n9iSxIyS9-FLilnRBlnznh2ldT2xGOCtA5LmYtSu6d3jv68djVwIaF3WDTeOqzkwux6qXAZ8tJl6WnHJot02qCW9fwMa_oU6Z50CQA_68yZGBGhFn4E465WoY1YqE_CgagfkEXq-o248LOip-fMYJSmvhFg_guL13ghBG2K5tjUcq5uhkJqP4f1838PkBcdKJQExT4_yZbBqHyOLYhwUWdBuipcZiYRJhWDod5UDsvjHj0Q6YOn_RqAz8wjyHTWuUJOyOf6CODB9fzOJdyWPy-WX2BeJuz9expQfyAIILQMP9IOLADIyU1JaK9DZ3Nrfam1NX8LOIJ4RjSLgSoQ7eCty9AzGGYkgNXa59K06SY6t62uy0-b_sfv1z6UChMbZizpY41hI88LeL8pdkZSSCgNFsDCe40B-LsQfORtzx8bAo7zqAjivReEM0PWiJRg4UjcCdoKxpqrjINrMfW0UHiv3oZcdfiaNFZ8qt0j0BO1DEwgiK792PotasN5ypM2ziAPFcoiVdPLsDEQevyiPg"
      resources:
        limits:
          memory: "4Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
      app: llm-node